import type { SVGItem } from './types';

/**
 * Array contendo a definição das badges da categoria ferramentas.
 */
export const ferramentasItems: SVGItem[] = [
  {
    id: 'badge-cursor',
    title: 'Cursor',
    filename: 'badges/ferramentas/badge-cursor.svg',
    alt: 'Badge Cursor',
    category: 'skills',
  },
  {
    id: 'badge-antigravity',
    title: 'Antigravity',
    filename: 'badges/ferramentas/badge-antigravity.svg',
    alt: 'Badge Antigravity',
    category: 'skills',
  },
  {
    id: 'badge-prometheus',
    title: 'Prometheus',
    filename: 'badges/ferramentas/badge-prometheus.svg',
    alt: 'Badge Prometheus',
    category: 'skills',
  },
  {
    id: 'badge-grafana',
    title: 'Grafana',
    filename: 'badges/ferramentas/badge-grafana.svg',
    alt: 'Badge Grafana',
    category: 'skills',
  },
  {
    id: 'badge-helm',
    title: 'Helm',
    filename: 'badges/ferramentas/badge-helm.svg',
    alt: 'Badge Helm',
    category: 'skills',
  },
  {
    id: 'badge-datadog',
    title: 'Datadog',
    filename: 'badges/ferramentas/badge-datadog.svg',
    alt: 'Badge Datadog',
    category: 'skills',
  },
  {
    id: 'badge-sentry',
    title: 'Sentry',
    filename: 'badges/ferramentas/badge-sentry.svg',
    alt: 'Badge Sentry',
    category: 'skills',
  },
  {
    id: 'badge-newrelic',
    title: 'New Relic',
    filename: 'badges/ferramentas/badge-newrelic.svg',
    alt: 'Badge New Relic',
    category: 'skills',
  },
  {
    id: 'badge-pagerduty',
    title: 'PagerDuty',
    filename: 'badges/ferramentas/badge-pagerduty.svg',
    alt: 'Badge PagerDuty',
    category: 'skills',
  },
  {
    id: 'badge-raycast',
    title: 'Raycast',
    filename: 'badges/ferramentas/badge-raycast.svg',
    alt: 'Badge Raycast',
    category: 'skills',
  },
  {
    id: 'badge-obsidian',
    title: 'Obsidian',
    filename: 'badges/ferramentas/badge-obsidian.svg',
    alt: 'Badge Obsidian',
    category: 'skills',
  },
  {
    id: 'badge-linear',
    title: 'Linear',
    filename: 'badges/ferramentas/badge-linear.svg',
    alt: 'Badge Linear',
    category: 'skills',
  },
  {
    id: 'badge-clickup',
    title: 'ClickUp',
    filename: 'badges/ferramentas/badge-clickup.svg',
    alt: 'Badge ClickUp',
    category: 'skills',
  },
  {
    id: 'badge-splunk',
    title: 'Splunk',
    filename: 'badges/ferramentas/badge-splunk.svg',
    alt: 'Badge Splunk',
    category: 'skills',
  },
  {
    id: 'badge-airflow',
    title: 'Airflow',
    filename: 'badges/ferramentas/badge-airflow.svg',
    alt: 'Badge Airflow',
    category: 'skills',
  },
  {
    id: 'badge-ansible',
    title: 'Ansible',
    filename: 'badges/ferramentas/badge-ansible.svg',
    alt: 'Badge Ansible',
    category: 'skills',
  },
  {
    id: 'badge-bitbucket',
    title: 'Bitbucket',
    filename: 'badges/ferramentas/badge-bitbucket.svg',
    alt: 'Badge Bitbucket',
    category: 'skills',
  },
  {
    id: 'badge-bun',
    title: 'Bun',
    filename: 'badges/ferramentas/badge-bun.svg',
    alt: 'Badge Bun',
    category: 'skills',
  },
  {
    id: 'badge-circleci',
    title: 'Circleci',
    filename: 'badges/ferramentas/badge-circleci.svg',
    alt: 'Badge Circleci',
    category: 'skills',
  },
  {
    id: 'badge-cypress',
    title: 'Cypress',
    filename: 'badges/ferramentas/badge-cypress.svg',
    alt: 'Badge Cypress',
    category: 'skills',
  },
  {
    id: 'badge-deno',
    title: 'Deno',
    filename: 'badges/ferramentas/badge-deno.svg',
    alt: 'Badge Deno',
    category: 'skills',
  },
  {
    id: 'badge-discord',
    title: 'Discord',
    filename: 'badges/ferramentas/badge-discord.svg',
    alt: 'Badge Discord',
    category: 'skills',
  },
  {
    id: 'badge-docker',
    title: 'Docker',
    filename: 'badges/ferramentas/badge-docker.svg',
    alt: 'Badge Docker',
    category: 'skills',
  },
  {
    id: 'badge-esbuild',
    title: 'Esbuild',
    filename: 'badges/ferramentas/badge-esbuild.svg',
    alt: 'Badge Esbuild',
    category: 'skills',
  },
  {
    id: 'badge-eslint',
    title: 'Eslint',
    filename: 'badges/ferramentas/badge-eslint.svg',
    alt: 'Badge Eslint',
    category: 'skills',
  },
  {
    id: 'badge-figma',
    title: 'Figma',
    filename: 'badges/ferramentas/badge-figma.svg',
    alt: 'Badge Figma',
    category: 'skills',
  },
  {
    id: 'badge-git',
    title: 'Git',
    filename: 'badges/ferramentas/badge-git.svg',
    alt: 'Badge Git',
    category: 'skills',
  },
  {
    id: 'badge-github-actions',
    title: 'Github Actions',
    filename: 'badges/ferramentas/badge-github-actions.svg',
    alt: 'Badge Github Actions',
    category: 'skills',
  },
  {
    id: 'badge-github',
    title: 'Github',
    filename: 'badges/ferramentas/badge-github.svg',
    alt: 'Badge Github',
    category: 'skills',
  },
  {
    id: 'badge-gitlab',
    title: 'Gitlab',
    filename: 'badges/ferramentas/badge-gitlab.svg',
    alt: 'Badge Gitlab',
    category: 'skills',
  },
  {
    id: 'badge-insomnia',
    title: 'Insomnia',
    filename: 'badges/ferramentas/badge-insomnia.svg',
    alt: 'Badge Insomnia',
    category: 'skills',
  },
  {
    id: 'badge-intellij',
    title: 'Intellij',
    filename: 'badges/ferramentas/badge-intellij.svg',
    alt: 'Badge Intellij',
    category: 'skills',
  },
  {
    id: 'badge-jenkins',
    title: 'Jenkins',
    filename: 'badges/ferramentas/badge-jenkins.svg',
    alt: 'Badge Jenkins',
    category: 'skills',
  },
  {
    id: 'badge-jest',
    title: 'Jest',
    filename: 'badges/ferramentas/badge-jest.svg',
    alt: 'Badge Jest',
    category: 'skills',
  },
  {
    id: 'badge-jira',
    title: 'Jira',
    filename: 'badges/ferramentas/badge-jira.svg',
    alt: 'Badge Jira',
    category: 'skills',
  },
  {
    id: 'badge-jupyter',
    title: 'Jupyter',
    filename: 'badges/ferramentas/badge-jupyter.svg',
    alt: 'Badge Jupyter',
    category: 'skills',
  },
  {
    id: 'badge-kubernetes',
    title: 'Kubernetes',
    filename: 'badges/ferramentas/badge-kubernetes.svg',
    alt: 'Badge Kubernetes',
    category: 'skills',
  },
  {
    id: 'badge-lerna',
    title: 'Lerna',
    filename: 'badges/ferramentas/badge-lerna.svg',
    alt: 'Badge Lerna',
    category: 'skills',
  },
  {
    id: 'badge-mocha',
    title: 'Mocha',
    filename: 'badges/ferramentas/badge-mocha.svg',
    alt: 'Badge Mocha',
    category: 'skills',
  },
  {
    id: 'badge-neovim',
    title: 'Neovim',
    filename: 'badges/ferramentas/badge-neovim.svg',
    alt: 'Badge Neovim',
    category: 'skills',
  },
  {
    id: 'badge-notion',
    title: 'Notion',
    filename: 'badges/ferramentas/badge-notion.svg',
    alt: 'Badge Notion',
    category: 'skills',
  },
  {
    id: 'badge-npm',
    title: 'Npm',
    filename: 'badges/ferramentas/badge-npm.svg',
    alt: 'Badge Npm',
    category: 'skills',
  },
  {
    id: 'badge-nx',
    title: 'Nx',
    filename: 'badges/ferramentas/badge-nx.svg',
    alt: 'Badge Nx',
    category: 'skills',
  },
  {
    id: 'badge-playwright',
    title: 'Playwright',
    filename: 'badges/ferramentas/badge-playwright.svg',
    alt: 'Badge Playwright',
    category: 'skills',
  },
  {
    id: 'badge-pnpm',
    title: 'Pnpm',
    filename: 'badges/ferramentas/badge-pnpm.svg',
    alt: 'Badge Pnpm',
    category: 'skills',
  },
  {
    id: 'badge-postman',
    title: 'Postman',
    filename: 'badges/ferramentas/badge-postman.svg',
    alt: 'Badge Postman',
    category: 'skills',
  },
  {
    id: 'badge-prettier',
    title: 'Prettier',
    filename: 'badges/ferramentas/badge-prettier.svg',
    alt: 'Badge Prettier',
    category: 'skills',
  },
  {
    id: 'badge-rollup',
    title: 'Rollup',
    filename: 'badges/ferramentas/badge-rollup.svg',
    alt: 'Badge Rollup',
    category: 'skills',
  },
];
