import type { SVGItem } from './types';

export const langsItems: SVGItem[] = [
  {
    id: 'badge-bash',
    title: 'Bash',
    filename: 'badges/langs/badge-bash.svg',
    alt: 'Badge Bash',
    category: 'skills',
  },
  {
    id: 'badge-shell',
    title: 'Shell',
    filename: 'badges/langs/badge-shell.svg',
    alt: 'Badge Shell',
    category: 'skills',
  },
  {
    id: 'badge-cobol',
    title: 'COBOL',
    filename: 'badges/langs/badge-cobol.svg',
    alt: 'Badge COBOL',
    category: 'skills',
  },
  {
    id: 'badge-crystal',
    title: 'Crystal',
    filename: 'badges/langs/badge-crystal.svg',
    alt: 'Badge Crystal',
    category: 'skills',
  },
  {
    id: 'badge-delphi',
    title: 'Delphi',
    filename: 'badges/langs/badge-delphi.svg',
    alt: 'Badge Delphi',
    category: 'skills',
  },
  {
    id: 'badge-erlang',
    title: 'Erlang',
    filename: 'badges/langs/badge-erlang.svg',
    alt: 'Badge Erlang',
    category: 'skills',
  },
  {
    id: 'badge-fortran',
    title: 'Fortran',
    filename: 'badges/langs/badge-fortran.svg',
    alt: 'Badge Fortran',
    category: 'skills',
  },
  {
    id: 'badge-fsharp',
    title: 'F#',
    filename: 'badges/langs/badge-fsharp.svg',
    alt: 'Badge F#',
    category: 'skills',
  },
  {
    id: 'badge-groovy',
    title: 'Groovy',
    filename: 'badges/langs/badge-groovy.svg',
    alt: 'Badge Groovy',
    category: 'skills',
  },
  {
    id: 'badge-matlab',
    title: 'MATLAB',
    filename: 'badges/langs/badge-matlab.svg',
    alt: 'Badge MATLAB',
    category: 'skills',
  },
  {
    id: 'badge-nim',
    title: 'Nim',
    filename: 'badges/langs/badge-nim.svg',
    alt: 'Badge Nim',
    category: 'skills',
  },
  {
    id: 'badge-objective-c',
    title: 'Objective-C',
    filename: 'badges/langs/badge-objective-c.svg',
    alt: 'Badge Objective-C',
    category: 'skills',
  },
  {
    id: 'badge-ocaml',
    title: 'OCaml',
    filename: 'badges/langs/badge-ocaml.svg',
    alt: 'Badge OCaml',
    category: 'skills',
  },
  {
    id: 'badge-powershell',
    title: 'PowerShell',
    filename: 'badges/langs/badge-powershell.svg',
    alt: 'Badge PowerShell',
    category: 'skills',
  },
  {
    id: 'badge-racket',
    title: 'Racket',
    filename: 'badges/langs/badge-racket.svg',
    alt: 'Badge Racket',
    category: 'skills',
  },
  {
    id: 'badge-sql',
    title: 'SQL',
    filename: 'badges/langs/badge-sql.svg',
    alt: 'Badge SQL',
    category: 'skills',
  },
  {
    id: 'badge-julia',
    title: 'Julia',
    filename: 'badges/langs/badge-julia.svg',
    alt: 'Badge Julia',
    category: 'skills',
  },
  {
    id: 'badge-zig',
    title: 'Zig',
    filename: 'badges/langs/badge-zig.svg',
    alt: 'Badge Zig',
    category: 'skills',
  },
  {
    id: 'badge-clojure',
    title: 'Clojure',
    filename: 'badges/langs/badge-clojure.svg',
    alt: 'Badge Clojure',
    category: 'skills',
  },
];
