import type { SVGItem } from './types';

export const tecnologiasItems: SVGItem[] = [
  {
    id: 'badge-astrobuild',
    title: 'Astro Build',
    filename: 'badges/tecnologias/badge-astrobuild.svg',
    alt: 'Badge Astro Build',
    category: 'skills',
  },
  {
    id: 'badge-blitzjs',
    title: 'Blitz.js',
    filename: 'badges/tecnologias/badge-blitzjs.svg',
    alt: 'Badge Blitz.js',
    category: 'skills',
  },
  {
    id: 'badge-bunrest',
    title: 'Bun Rest',
    filename: 'badges/tecnologias/badge-bunrest.svg',
    alt: 'Badge Bun Rest',
    category: 'skills',
  },
  {
    id: 'badge-elysia',
    title: 'Elysia',
    filename: 'badges/tecnologias/badge-elysia.svg',
    alt: 'Badge Elysia',
    category: 'skills',
  },
  {
    id: 'badge-nhost',
    title: 'Nhost',
    filename: 'badges/tecnologias/badge-nhost.svg',
    alt: 'Badge Nhost',
    category: 'skills',
  },
  {
    id: 'badge-qwikcity',
    title: 'Qwik City',
    filename: 'badges/tecnologias/badge-qwikcity.svg',
    alt: 'Badge Qwik City',
    category: 'skills',
  },
  {
    id: 'badge-remult',
    title: 'Remult',
    filename: 'badges/tecnologias/badge-remult.svg',
    alt: 'Badge Remult',
    category: 'skills',
  },
  {
    id: 'badge-solidstart',
    title: 'SolidStart',
    filename: 'badges/tecnologias/badge-solidstart.svg',
    alt: 'Badge SolidStart',
    category: 'skills',
  },
  {
    id: 'badge-turso',
    title: 'Turso',
    filename: 'badges/tecnologias/badge-turso.svg',
    alt: 'Badge Turso',
    category: 'skills',
  },
  {
    id: 'badge-umijs',
    title: 'UmiJS',
    filename: 'badges/tecnologias/badge-umijs.svg',
    alt: 'Badge UmiJS',
    category: 'skills',
  },
  {
    id: 'badge-javascript',
    title: 'JavaScript',
    filename: 'badges/tecnologias/badge-javascript.svg',
    alt: 'Badge JavaScript',
    category: 'skills',
  },
  {
    id: 'badge-typescript',
    title: 'TypeScript',
    filename: 'badges/tecnologias/badge-typescript.svg',
    alt: 'Badge TypeScript',
    category: 'skills',
  },
  {
    id: 'badge-python',
    title: 'Python',
    filename: 'badges/tecnologias/badge-python.svg',
    alt: 'Badge Python',
    category: 'skills',
  },
  {
    id: 'badge-java',
    title: 'Java',
    filename: 'badges/tecnologias/badge-java.svg',
    alt: 'Badge Java',
    category: 'skills',
  },
  {
    id: 'badge-csharp',
    title: 'C#',
    filename: 'badges/tecnologias/badge-csharp.svg',
    alt: 'Badge C#',
    category: 'skills',
  },
  {
    id: 'badge-go',
    title: 'Golang',
    filename: 'badges/tecnologias/badge-go.svg',
    alt: 'Badge Golang',
    category: 'skills',
  },
  {
    id: 'badge-rust',
    title: 'Rust',
    filename: 'badges/tecnologias/badge-rust.svg',
    alt: 'Badge Rust',
    category: 'skills',
  },
  {
    id: 'badge-php',
    title: 'PHP',
    filename: 'badges/tecnologias/badge-php.svg',
    alt: 'Badge PHP',
    category: 'skills',
  },
  {
    id: 'badge-ruby',
    title: 'Ruby',
    filename: 'badges/tecnologias/badge-ruby.svg',
    alt: 'Badge Ruby',
    category: 'skills',
  },
  {
    id: 'badge-swift',
    title: 'Swift',
    filename: 'badges/tecnologias/badge-swift.svg',
    alt: 'Badge Swift',
    category: 'skills',
  },
  {
    id: 'badge-kotlin',
    title: 'Kotlin',
    filename: 'badges/tecnologias/badge-kotlin.svg',
    alt: 'Badge Kotlin',
    category: 'skills',
  },
  {
    id: 'badge-cpp',
    title: 'C++',
    filename: 'badges/tecnologias/badge-cpp.svg',
    alt: 'Badge C++',
    category: 'skills',
  },
  {
    id: 'badge-c',
    title: 'C',
    filename: 'badges/tecnologias/badge-c.svg',
    alt: 'Badge C',
    category: 'skills',
  },
  {
    id: 'badge-scala',
    title: 'Scala',
    filename: 'badges/tecnologias/badge-scala.svg',
    alt: 'Badge Scala',
    category: 'skills',
  },
  {
    id: 'badge-elixir',
    title: 'Elixir',
    filename: 'badges/tecnologias/badge-elixir.svg',
    alt: 'Badge Elixir',
    category: 'skills',
  },
  {
    id: 'badge-haskell',
    title: 'Haskell',
    filename: 'badges/tecnologias/badge-haskell.svg',
    alt: 'Badge Haskell',
    category: 'skills',
  },
  {
    id: 'badge-lua',
    title: 'Lua',
    filename: 'badges/tecnologias/badge-lua.svg',
    alt: 'Badge Lua',
    category: 'skills',
  },
  {
    id: 'badge-dart',
    title: 'Dart',
    filename: 'badges/tecnologias/badge-dart.svg',
    alt: 'Badge Dart',
    category: 'skills',
  },
  {
    id: 'badge-r',
    title: 'R',
    filename: 'badges/tecnologias/badge-r.svg',
    alt: 'Badge R',
    category: 'skills',
  },
  {
    id: 'badge-perl',
    title: 'Perl',
    filename: 'badges/tecnologias/badge-perl.svg',
    alt: 'Badge Perl',
    category: 'skills',
  },
  {
    id: 'badge-html',
    title: 'HTML5',
    filename: 'badges/tecnologias/badge-html.svg',
    alt: 'Badge HTML5',
    category: 'skills',
  },
  {
    id: 'badge-css',
    title: 'CSS3',
    filename: 'badges/tecnologias/badge-css.svg',
    alt: 'Badge CSS3',
    category: 'skills',
  },
  {
    id: 'badge-react',
    title: 'React',
    filename: 'badges/tecnologias/badge-react.svg',
    alt: 'Badge React',
    category: 'skills',
  },
  {
    id: 'badge-vue',
    title: 'Vue.js',
    filename: 'badges/tecnologias/badge-vue.svg',
    alt: 'Badge Vue.js',
    category: 'skills',
  },
  {
    id: 'badge-angular',
    title: 'Angular',
    filename: 'badges/tecnologias/badge-angular.svg',
    alt: 'Badge Angular',
    category: 'skills',
  },
  {
    id: 'badge-nextjs',
    title: 'Next.js',
    filename: 'badges/tecnologias/badge-nextjs.svg',
    alt: 'Badge Next.js',
    category: 'skills',
  },
  {
    id: 'badge-nuxt',
    title: 'Nuxt.js',
    filename: 'badges/tecnologias/badge-nuxt.svg',
    alt: 'Badge Nuxt.js',
    category: 'skills',
  },
  {
    id: 'badge-svelte',
    title: 'Svelte',
    filename: 'badges/tecnologias/badge-svelte.svg',
    alt: 'Badge Svelte',
    category: 'skills',
  },
  {
    id: 'badge-tailwind',
    title: 'Tailwind CSS',
    filename: 'badges/tecnologias/badge-tailwind.svg',
    alt: 'Badge Tailwind CSS',
    category: 'skills',
  },
  {
    id: 'badge-sass',
    title: 'Sass',
    filename: 'badges/tecnologias/badge-sass.svg',
    alt: 'Badge Sass',
    category: 'skills',
  },
  {
    id: 'badge-remix',
    title: 'Remix',
    filename: 'badges/tecnologias/badge-remix.svg',
    alt: 'Badge Remix',
    category: 'skills',
  },
  {
    id: 'badge-astro',
    title: 'Astro',
    filename: 'badges/tecnologias/badge-astro.svg',
    alt: 'Badge Astro',
    category: 'skills',
  },
  {
    id: 'badge-solid',
    title: 'SolidJS',
    filename: 'badges/tecnologias/badge-solid.svg',
    alt: 'Badge SolidJS',
    category: 'skills',
  },
  {
    id: 'badge-qwik',
    title: 'Qwik',
    filename: 'badges/tecnologias/badge-qwik.svg',
    alt: 'Badge Qwik',
    category: 'skills',
  },
  {
    id: 'badge-htmx',
    title: 'HTMX',
    filename: 'badges/tecnologias/badge-htmx.svg',
    alt: 'Badge HTMX',
    category: 'skills',
  },
  {
    id: 'badge-bootstrap',
    title: 'Bootstrap',
    filename: 'badges/tecnologias/badge-bootstrap.svg',
    alt: 'Badge Bootstrap',
    category: 'skills',
  },
  {
    id: 'badge-material-ui',
    title: 'Material UI',
    filename: 'badges/tecnologias/badge-material-ui.svg',
    alt: 'Badge Material UI',
    category: 'skills',
  },
  {
    id: 'badge-chakra',
    title: 'Chakra UI',
    filename: 'badges/tecnologias/badge-chakra.svg',
    alt: 'Badge Chakra UI',
    category: 'skills',
  },
  {
    id: 'badge-styled-components',
    title: 'Styled Components',
    filename: 'badges/tecnologias/badge-styled-components.svg',
    alt: 'Badge Styled Components',
    category: 'skills',
  },
  {
    id: 'badge-storybook',
    title: 'Storybook',
    filename: 'badges/tecnologias/badge-storybook.svg',
    alt: 'Badge Storybook',
    category: 'skills',
  },
  {
    id: 'badge-nodejs',
    title: 'Node.js',
    filename: 'badges/tecnologias/badge-nodejs.svg',
    alt: 'Badge Node.js',
    category: 'skills',
  },
  {
    id: 'badge-express',
    title: 'Express',
    filename: 'badges/tecnologias/badge-express.svg',
    alt: 'Badge Express',
    category: 'skills',
  },
  {
    id: 'badge-nestjs',
    title: 'NestJS',
    filename: 'badges/tecnologias/badge-nestjs.svg',
    alt: 'Badge NestJS',
    category: 'skills',
  },
  {
    id: 'badge-django',
    title: 'Django',
    filename: 'badges/tecnologias/badge-django.svg',
    alt: 'Badge Django',
    category: 'skills',
  },
  {
    id: 'badge-laravel',
    title: 'Laravel',
    filename: 'badges/tecnologias/badge-laravel.svg',
    alt: 'Badge Laravel',
    category: 'skills',
  },
  {
    id: 'badge-spring',
    title: 'Spring',
    filename: 'badges/tecnologias/badge-spring.svg',
    alt: 'Badge Spring',
    category: 'skills',
  },
  {
    id: 'badge-fastapi',
    title: 'FastAPI',
    filename: 'badges/tecnologias/badge-fastapi.svg',
    alt: 'Badge FastAPI',
    category: 'skills',
  },
  {
    id: 'badge-flask',
    title: 'Flask',
    filename: 'badges/tecnologias/badge-flask.svg',
    alt: 'Badge Flask',
    category: 'skills',
  },
  {
    id: 'badge-rails',
    title: 'Ruby on Rails',
    filename: 'badges/tecnologias/badge-rails.svg',
    alt: 'Badge Ruby on Rails',
    category: 'skills',
  },
  {
    id: 'badge-dotnet',
    title: '.NET',
    filename: 'badges/tecnologias/badge-dotnet.svg',
    alt: 'Badge .NET',
    category: 'skills',
  },
  {
    id: 'badge-phoenix',
    title: 'Phoenix',
    filename: 'badges/tecnologias/badge-phoenix.svg',
    alt: 'Badge Phoenix',
    category: 'skills',
  },
  {
    id: 'badge-gin',
    title: 'Gin',
    filename: 'badges/tecnologias/badge-gin.svg',
    alt: 'Badge Gin',
    category: 'skills',
  },
  {
    id: 'badge-fiber',
    title: 'Fiber',
    filename: 'badges/tecnologias/badge-fiber.svg',
    alt: 'Badge Fiber',
    category: 'skills',
  },
  {
    id: 'badge-deno',
    title: 'Deno',
    filename: 'badges/tecnologias/badge-deno.svg',
    alt: 'Badge Deno',
    category: 'skills',
  },
  {
    id: 'badge-bun',
    title: 'Bun',
    filename: 'badges/tecnologias/badge-bun.svg',
    alt: 'Badge Bun',
    category: 'skills',
  },
  {
    id: 'badge-mongodb',
    title: 'MongoDB',
    filename: 'badges/tecnologias/badge-mongodb.svg',
    alt: 'Badge MongoDB',
    category: 'skills',
  },
  {
    id: 'badge-postgresql',
    title: 'PostgreSQL',
    filename: 'badges/tecnologias/badge-postgresql.svg',
    alt: 'Badge PostgreSQL',
    category: 'skills',
  },
  {
    id: 'badge-mysql',
    title: 'MySQL',
    filename: 'badges/tecnologias/badge-mysql.svg',
    alt: 'Badge MySQL',
    category: 'skills',
  },
  {
    id: 'badge-redis',
    title: 'Redis',
    filename: 'badges/tecnologias/badge-redis.svg',
    alt: 'Badge Redis',
    category: 'skills',
  },
  {
    id: 'badge-firebase',
    title: 'Firebase',
    filename: 'badges/tecnologias/badge-firebase.svg',
    alt: 'Badge Firebase',
    category: 'skills',
  },
  {
    id: 'badge-supabase',
    title: 'Supabase',
    filename: 'badges/tecnologias/badge-supabase.svg',
    alt: 'Badge Supabase',
    category: 'skills',
  },
  {
    id: 'badge-prisma',
    title: 'Prisma',
    filename: 'badges/tecnologias/badge-prisma.svg',
    alt: 'Badge Prisma',
    category: 'skills',
  },
  {
    id: 'badge-sqlite',
    title: 'SQLite',
    filename: 'badges/tecnologias/badge-sqlite.svg',
    alt: 'Badge SQLite',
    category: 'skills',
  },
  {
    id: 'badge-mariadb',
    title: 'MariaDB',
    filename: 'badges/tecnologias/badge-mariadb.svg',
    alt: 'Badge MariaDB',
    category: 'skills',
  },
  {
    id: 'badge-cassandra',
    title: 'Cassandra',
    filename: 'badges/tecnologias/badge-cassandra.svg',
    alt: 'Badge Cassandra',
    category: 'skills',
  },
  {
    id: 'badge-elasticsearch',
    title: 'Elasticsearch',
    filename: 'badges/tecnologias/badge-elasticsearch.svg',
    alt: 'Badge Elasticsearch',
    category: 'skills',
  },
  {
    id: 'badge-dynamodb',
    title: 'DynamoDB',
    filename: 'badges/tecnologias/badge-dynamodb.svg',
    alt: 'Badge DynamoDB',
    category: 'skills',
  },
  {
    id: 'badge-planetscale',
    title: 'PlanetScale',
    filename: 'badges/tecnologias/badge-planetscale.svg',
    alt: 'Badge PlanetScale',
    category: 'skills',
  },
  {
    id: 'badge-drizzle',
    title: 'Drizzle',
    filename: 'badges/tecnologias/badge-drizzle.svg',
    alt: 'Badge Drizzle ORM',
    category: 'skills',
  },
  {
    id: 'badge-typeorm',
    title: 'TypeORM',
    filename: 'badges/tecnologias/badge-typeorm.svg',
    alt: 'Badge TypeORM',
    category: 'skills',
  },
  {
    id: 'badge-docker',
    title: 'Docker',
    filename: 'badges/tecnologias/badge-docker.svg',
    alt: 'Badge Docker',
    category: 'skills',
  },
  {
    id: 'badge-kubernetes',
    title: 'Kubernetes',
    filename: 'badges/tecnologias/badge-kubernetes.svg',
    alt: 'Badge Kubernetes',
    category: 'skills',
  },
  {
    id: 'badge-aws',
    title: 'AWS',
    filename: 'badges/tecnologias/badge-aws.svg',
    alt: 'Badge AWS',
    category: 'skills',
  },
  {
    id: 'badge-terraform',
    title: 'Terraform',
    filename: 'badges/tecnologias/badge-terraform.svg',
    alt: 'Badge Terraform',
    category: 'skills',
  },
  {
    id: 'badge-jenkins',
    title: 'Jenkins',
    filename: 'badges/tecnologias/badge-jenkins.svg',
    alt: 'Badge Jenkins',
    category: 'skills',
  },
  {
    id: 'badge-vercel',
    title: 'Vercel',
    filename: 'badges/tecnologias/badge-vercel.svg',
    alt: 'Badge Vercel',
    category: 'skills',
  },
  {
    id: 'badge-netlify',
    title: 'Netlify',
    filename: 'badges/tecnologias/badge-netlify.svg',
    alt: 'Badge Netlify',
    category: 'skills',
  },
  {
    id: 'badge-azure',
    title: 'Azure',
    filename: 'badges/tecnologias/badge-azure.svg',
    alt: 'Badge Azure',
    category: 'skills',
  },
  {
    id: 'badge-gcp',
    title: 'Google Cloud',
    filename: 'badges/tecnologias/badge-gcp.svg',
    alt: 'Badge Google Cloud',
    category: 'skills',
  },
  {
    id: 'badge-digitalocean',
    title: 'DigitalOcean',
    filename: 'badges/tecnologias/badge-digitalocean.svg',
    alt: 'Badge DigitalOcean',
    category: 'skills',
  },
  {
    id: 'badge-cloudflare',
    title: 'Cloudflare',
    filename: 'badges/tecnologias/badge-cloudflare.svg',
    alt: 'Badge Cloudflare',
    category: 'skills',
  },
  {
    id: 'badge-github-actions',
    title: 'GitHub Actions',
    filename: 'badges/tecnologias/badge-github-actions.svg',
    alt: 'Badge GitHub Actions',
    category: 'skills',
  },
  {
    id: 'badge-circleci',
    title: 'CircleCI',
    filename: 'badges/tecnologias/badge-circleci.svg',
    alt: 'Badge CircleCI',
    category: 'skills',
  },
  {
    id: 'badge-travisci',
    title: 'Travis CI',
    filename: 'badges/tecnologias/badge-travisci.svg',
    alt: 'Badge Travis CI',
    category: 'skills',
  },
  {
    id: 'badge-ansible',
    title: 'Ansible',
    filename: 'badges/tecnologias/badge-ansible.svg',
    alt: 'Badge Ansible',
    category: 'skills',
  },
  {
    id: 'badge-nginx',
    title: 'Nginx',
    filename: 'badges/tecnologias/badge-nginx.svg',
    alt: 'Badge Nginx',
    category: 'skills',
  },
  {
    id: 'badge-railway',
    title: 'Railway',
    filename: 'badges/tecnologias/badge-railway.svg',
    alt: 'Badge Railway',
    category: 'skills',
  },
  {
    id: 'badge-render',
    title: 'Render',
    filename: 'badges/tecnologias/badge-render.svg',
    alt: 'Badge Render',
    category: 'skills',
  },
  {
    id: 'badge-fly',
    title: 'Fly.io',
    filename: 'badges/tecnologias/badge-fly.svg',
    alt: 'Badge Fly.io',
    category: 'skills',
  },
  {
    id: 'badge-git',
    title: 'Git',
    filename: 'badges/tecnologias/badge-git.svg',
    alt: 'Badge Git',
    category: 'skills',
  },
  {
    id: 'badge-github',
    title: 'GitHub',
    filename: 'badges/tecnologias/badge-github.svg',
    alt: 'Badge GitHub',
    category: 'skills',
  },
  {
    id: 'badge-gitlab',
    title: 'GitLab',
    filename: 'badges/tecnologias/badge-gitlab.svg',
    alt: 'Badge GitLab',
    category: 'skills',
  },
  {
    id: 'badge-vscode',
    title: 'VS Code',
    filename: 'badges/tecnologias/badge-vscode.svg',
    alt: 'Badge VS Code',
    category: 'skills',
  },
  {
    id: 'badge-figma',
    title: 'Figma',
    filename: 'badges/tecnologias/badge-figma.svg',
    alt: 'Badge Figma',
    category: 'skills',
  },
  {
    id: 'badge-linux',
    title: 'Linux',
    filename: 'badges/tecnologias/badge-linux.svg',
    alt: 'Badge Linux',
    category: 'skills',
  },
  {
    id: 'badge-neovim',
    title: 'Neovim',
    filename: 'badges/tecnologias/badge-neovim.svg',
    alt: 'Badge Neovim',
    category: 'skills',
  },
  {
    id: 'badge-intellij',
    title: 'IntelliJ IDEA',
    filename: 'badges/tecnologias/badge-intellij.svg',
    alt: 'Badge IntelliJ IDEA',
    category: 'skills',
  },
  {
    id: 'badge-postman',
    title: 'Postman',
    filename: 'badges/tecnologias/badge-postman.svg',
    alt: 'Badge Postman',
    category: 'skills',
  },
  {
    id: 'badge-insomnia',
    title: 'Insomnia',
    filename: 'badges/tecnologias/badge-insomnia.svg',
    alt: 'Badge Insomnia',
    category: 'skills',
  },
  {
    id: 'badge-notion',
    title: 'Notion',
    filename: 'badges/tecnologias/badge-notion.svg',
    alt: 'Badge Notion',
    category: 'skills',
  },
  {
    id: 'badge-slack',
    title: 'Slack',
    filename: 'badges/tecnologias/badge-slack.svg',
    alt: 'Badge Slack',
    category: 'skills',
  },
  {
    id: 'badge-discord',
    title: 'Discord',
    filename: 'badges/tecnologias/badge-discord.svg',
    alt: 'Badge Discord',
    category: 'skills',
  },
  {
    id: 'badge-jira',
    title: 'Jira',
    filename: 'badges/tecnologias/badge-jira.svg',
    alt: 'Badge Jira',
    category: 'skills',
  },
  {
    id: 'badge-bitbucket',
    title: 'Bitbucket',
    filename: 'badges/tecnologias/badge-bitbucket.svg',
    alt: 'Badge Bitbucket',
    category: 'skills',
  },
  {
    id: 'badge-npm',
    title: 'NPM',
    filename: 'badges/tecnologias/badge-npm.svg',
    alt: 'Badge NPM',
    category: 'skills',
  },
  {
    id: 'badge-yarn',
    title: 'Yarn',
    filename: 'badges/tecnologias/badge-yarn.svg',
    alt: 'Badge Yarn',
    category: 'skills',
  },
  {
    id: 'badge-pnpm',
    title: 'PNPM',
    filename: 'badges/tecnologias/badge-pnpm.svg',
    alt: 'Badge PNPM',
    category: 'skills',
  },
  {
    id: 'badge-webpack',
    title: 'Webpack',
    filename: 'badges/tecnologias/badge-webpack.svg',
    alt: 'Badge Webpack',
    category: 'skills',
  },
  {
    id: 'badge-vite',
    title: 'Vite',
    filename: 'badges/tecnologias/badge-vite.svg',
    alt: 'Badge Vite',
    category: 'skills',
  },
  {
    id: 'badge-rollup',
    title: 'Rollup',
    filename: 'badges/tecnologias/badge-rollup.svg',
    alt: 'Badge Rollup',
    category: 'skills',
  },
  {
    id: 'badge-esbuild',
    title: 'esbuild',
    filename: 'badges/tecnologias/badge-esbuild.svg',
    alt: 'Badge esbuild',
    category: 'skills',
  },
  {
    id: 'badge-turbo',
    title: 'Turborepo',
    filename: 'badges/tecnologias/badge-turbo.svg',
    alt: 'Badge Turborepo',
    category: 'skills',
  },
  {
    id: 'badge-nx',
    title: 'Nx',
    filename: 'badges/tecnologias/badge-nx.svg',
    alt: 'Badge Nx',
    category: 'skills',
  },
  {
    id: 'badge-lerna',
    title: 'Lerna',
    filename: 'badges/tecnologias/badge-lerna.svg',
    alt: 'Badge Lerna',
    category: 'skills',
  },
  {
    id: 'badge-gradle',
    title: 'Gradle',
    filename: 'badges/tecnologias/badge-gradle.svg',
    alt: 'Badge Gradle',
    category: 'skills',
  },
  {
    id: 'badge-maven',
    title: 'Maven',
    filename: 'badges/tecnologias/badge-maven.svg',
    alt: 'Badge Maven',
    category: 'skills',
  },
  {
    id: 'badge-eslint',
    title: 'ESLint',
    filename: 'badges/tecnologias/badge-eslint.svg',
    alt: 'Badge ESLint',
    category: 'skills',
  },
  {
    id: 'badge-prettier',
    title: 'Prettier',
    filename: 'badges/tecnologias/badge-prettier.svg',
    alt: 'Badge Prettier',
    category: 'skills',
  },
  {
    id: 'badge-jest',
    title: 'Jest',
    filename: 'badges/tecnologias/badge-jest.svg',
    alt: 'Badge Jest',
    category: 'skills',
  },
  {
    id: 'badge-cypress',
    title: 'Cypress',
    filename: 'badges/tecnologias/badge-cypress.svg',
    alt: 'Badge Cypress',
    category: 'skills',
  },
  {
    id: 'badge-vitest',
    title: 'Vitest',
    filename: 'badges/tecnologias/badge-vitest.svg',
    alt: 'Badge Vitest',
    category: 'skills',
  },
  {
    id: 'badge-playwright',
    title: 'Playwright',
    filename: 'badges/tecnologias/badge-playwright.svg',
    alt: 'Badge Playwright',
    category: 'skills',
  },
  {
    id: 'badge-testing-library',
    title: 'Testing Library',
    filename: 'badges/tecnologias/badge-testing-library.svg',
    alt: 'Badge Testing Library',
    category: 'skills',
  },
  {
    id: 'badge-mocha',
    title: 'Mocha',
    filename: 'badges/tecnologias/badge-mocha.svg',
    alt: 'Badge Mocha',
    category: 'skills',
  },
  {
    id: 'badge-selenium',
    title: 'Selenium',
    filename: 'badges/tecnologias/badge-selenium.svg',
    alt: 'Badge Selenium',
    category: 'skills',
  },
  {
    id: 'badge-sonarqube',
    title: 'SonarQube',
    filename: 'badges/tecnologias/badge-sonarqube.svg',
    alt: 'Badge SonarQube',
    category: 'skills',
  },
  {
    id: 'badge-graphql',
    title: 'GraphQL',
    filename: 'badges/tecnologias/badge-graphql.svg',
    alt: 'Badge GraphQL',
    category: 'skills',
  },
  {
    id: 'badge-flutter',
    title: 'Flutter',
    filename: 'badges/tecnologias/badge-flutter.svg',
    alt: 'Badge Flutter',
    category: 'skills',
  },
  {
    id: 'badge-react-native',
    title: 'React Native',
    filename: 'badges/tecnologias/badge-react-native.svg',
    alt: 'Badge React Native',
    category: 'skills',
  },
  {
    id: 'badge-expo',
    title: 'Expo',
    filename: 'badges/tecnologias/badge-expo.svg',
    alt: 'Badge Expo',
    category: 'skills',
  },
  {
    id: 'badge-ionic',
    title: 'Ionic',
    filename: 'badges/tecnologias/badge-ionic.svg',
    alt: 'Badge Ionic',
    category: 'skills',
  },
  {
    id: 'badge-rest',
    title: 'REST API',
    filename: 'badges/tecnologias/badge-rest.svg',
    alt: 'Badge REST API',
    category: 'skills',
  },
  {
    id: 'badge-trpc',
    title: 'tRPC',
    filename: 'badges/tecnologias/badge-trpc.svg',
    alt: 'Badge tRPC',
    category: 'skills',
  },
  {
    id: 'badge-grpc',
    title: 'gRPC',
    filename: 'badges/tecnologias/badge-grpc.svg',
    alt: 'Badge gRPC',
    category: 'skills',
  },
  {
    id: 'badge-websocket',
    title: 'WebSocket',
    filename: 'badges/tecnologias/badge-websocket.svg',
    alt: 'Badge WebSocket',
    category: 'skills',
  },
  {
    id: 'badge-socketio',
    title: 'Socket.io',
    filename: 'badges/tecnologias/badge-socketio.svg',
    alt: 'Badge Socket.io',
    category: 'skills',
  },
  {
    id: 'badge-rabbitmq',
    title: 'RabbitMQ',
    filename: 'badges/tecnologias/badge-rabbitmq.svg',
    alt: 'Badge RabbitMQ',
    category: 'skills',
  },
  {
    id: 'badge-kafka',
    title: 'Kafka',
    filename: 'badges/tecnologias/badge-kafka.svg',
    alt: 'Badge Kafka',
    category: 'skills',
  },
  {
    id: 'badge-tensorflow',
    title: 'TensorFlow',
    filename: 'badges/tecnologias/badge-tensorflow.svg',
    alt: 'Badge TensorFlow',
    category: 'skills',
  },
  {
    id: 'badge-pytorch',
    title: 'PyTorch',
    filename: 'badges/tecnologias/badge-pytorch.svg',
    alt: 'Badge PyTorch',
    category: 'skills',
  },
  {
    id: 'badge-openai',
    title: 'OpenAI',
    filename: 'badges/tecnologias/badge-openai.svg',
    alt: 'Badge OpenAI',
    category: 'skills',
  },
  {
    id: 'badge-langchain',
    title: 'LangChain',
    filename: 'badges/tecnologias/badge-langchain.svg',
    alt: 'Badge LangChain',
    category: 'skills',
  },
  {
    id: 'badge-huggingface',
    title: 'Hugging Face',
    filename: 'badges/tecnologias/badge-huggingface.svg',
    alt: 'Badge Hugging Face',
    category: 'skills',
  },
  {
    id: 'badge-pandas',
    title: 'Pandas',
    filename: 'badges/tecnologias/badge-pandas.svg',
    alt: 'Badge Pandas',
    category: 'skills',
  },
  {
    id: 'badge-numpy',
    title: 'NumPy',
    filename: 'badges/tecnologias/badge-numpy.svg',
    alt: 'Badge NumPy',
    category: 'skills',
  },
  {
    id: 'badge-jupyter',
    title: 'Jupyter',
    filename: 'badges/tecnologias/badge-jupyter.svg',
    alt: 'Badge Jupyter',
    category: 'skills',
  },
];
